
DATA:

    task : EMOTION
    task_dict: {'EMOTION': 176, 'GAMBLING': 253, 'LANGUAGE': 316, 'MOTOR': 284, 'RELATIONAL': 232, 'SOCIAL': 274, 'WM': 405}   

    fname: /home/lin/Projects/Data/EMOTION_Random_Subj_50_Sample_2500000_Whole_Brain.mat
    attrname: ['whole_brain_train_samples', 'whole_brain_test_samples','sample_group']

    data_dir: /home/lin/Data/Autoencoder/
    result_dir: results/

    test_data_dir: /home/lin/Projects/Data/
    test_attrname: ['whole_brain']


TRAIN:
    
    epochs : 100
    batch_size : 128
    momentum: 0.9
    weight_decay: 0.00005
    print_freq: 100


MODEL:

    kernel_size: [21, 9, 9, 9]
    kernel_num: [32, 64, 128, 256]
    latent_size: [16, 16, 16, 16]

    model_dir: models/





